spring.datasource.url=jdbc:postgresql://postgres:5432/appointment_booking
spring.datasource.username=postgres
spring.datasource.password=Tuit034911#.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.secret=appointment_booking_secret_key_ps19_2026_very_long
jwt.expiration=86400000

spring.data.mongodb.uri=mongodb+srv://rathernot787735_db_user:TkCby9q1vvvfLNmK@medibook.nhipgbg.mongodb.net/medibook_data?retryWrites=true&w=majority&appName=MediBook&ssl=true&sslInvalidHostNameAllowed=true&tlsInsecure=true
spring.data.mongodb.database=medibook_data
